# Generated by Django 2.1 on 2021-03-19 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0003_auto_20210310_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='host',
            name='buy_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='购置日期'),
        ),
    ]
