# Generated by Django 2.1 on 2021-03-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0004_auto_20210319_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'managed': False, 'permissions': (('monitor_monitor', 'can view monitor'),)},
        ),
    ]
