# Generated by Django 2.1 on 2021-03-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0005_auto_20210319_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'managed': False, 'permissions': (('monitor.monitor', 'can view monitor'),)},
        ),
    ]
